apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "library-chart.fullname" . }}-nginx-config
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen 80;
        
        location / {
            proxy_pass http://localhost:4213;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_read_timeout 300;
            proxy_connect_timeout 300;
        }
    }