apiVersion: v1
kind: Secret
metadata:
  name: {{ include "library-chart.secretNameToken" . }}
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.global.authentication.enabled }}
  MARIMO_TOKEN: {{ .Values.global.authentication.token | default (randAlphaNum 32) | quote }}
  {{- else }}
  MARIMO_TOKEN: ""
  {{- end }}
