apiVersion: v1
kind: Service
metadata:
  name: {{ include "library-chart.fullname" . }}
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.networking.type }}
  {{- if .Values.networking.clusterIP }}
  clusterIP: {{ .Values.networking.clusterIP }}
  {{- end }}
  ports:
    - port: {{ .Values.networking.service.port }}
      targetPort: {{ default .Values.networking.service.port .Values.networking.service.targetPort }}
      protocol: TCP
      name: main
    - port: 80
      targetPort: 80
      protocol: TCP
      name: nginx-proxy
    - port: 4213
      targetPort: 4213
      protocol: TCP
      name: duckdb-ui
    {{- range $userPort := $userPorts }}
    - port: {{ $userPort }}
      targetPort: {{ $userPort }}
      protocol: TCP
      name: {{ printf "user-%d" (int $userPort) | quote }}
    {{- end }}
    {{ if .Values.spark }}
    {{ if .Values.spark.sparkui }}
    {{ if .Values.networking.sparkui }}
    - port: {{ .Values.networking.sparkui.port }}
      targetPort: {{ .Values.networking.sparkui.port }}
      protocol: TCP
      name: sparkui
    {{- end }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "library-chart.selectorLabels" . | nindent 4 }}
{{- end -}}
{{- end }}