apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "marimo.fullname" . }}-configmap
  labels:
    {{- include "marimo.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.environment }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}