apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "marimo.fullname" . }}
  labels:
    app: {{ include "marimo.name" . }}
    chart: {{ include "marimo.chart" . }}
    release: {{ .Release.Name }}
    onyxia/service: "true"
    onyxia/type: "service"
  annotations:
    debug-image-repo: {{ .Values.image.repository }}
    debug-image-tag: {{ .Values.image.tag }}
    onyxia/service: "true"
    onyxia/service-type: "http"
    onyxia/service-port: "8080"
    onyxia/type: "service"
    onyxia/friendly-name: "Marimo"
    onyxia/description: "Marimo is a reactive Python notebook that's designed to be used both as an interactive development environment and as a data app framework."
    onyxia/url: "https://marimo-${ONYXIA_RANDOM_SUBDOMAIN}.${ONYXIA_DOMAIN}"
    onyxia/icon: "https://raw.githubusercontent.com/marimo-team/marimo/main/docs/_static/marimo.svg"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "marimo.name" . }}
      release: {{ .Release.Name }}
      onyxia/service: "true"
  template:
    metadata:
      labels:
        app: {{ include "marimo.name" . }}
        release: {{ .Release.Name }}
        onyxia/service: "true"
        onyxia/type: "service"
      annotations:
        onyxia/service: "true"
        onyxia/service-port: "8080"
        onyxia/service-type: "http"
        onyxia/type: "service"
        onyxia/friendly-name: "Marimo"
        onyxia/description: "Marimo is a reactive Python notebook that's designed to be used both as an interactive development environment and as a data app framework."
        onyxia/url: "https://marimo-${ONYXIA_RANDOM_SUBDOMAIN}.${ONYXIA_DOMAIN}"
        onyxia/icon: "https://raw.githubusercontent.com/marimo-team/marimo/main/docs/_static/marimo.svg"
    spec:
      serviceAccountName: {{ include "marimo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: MARIMO_PORT
              value: "8080"
            - name: MARIMO_HOST
              value: "0.0.0.0"
              {{- range $key, $value := .Values.onyxia.environment }}
              {{- if not (or (eq $key "ONYXIA_URL") (eq $key "ONYXIA_RANDOM_SUBDOMAIN") (eq $key "ONYXIA_DOMAIN")) }}
            - name: {{ $key }}
              value: {{ $value | quote }}
              {{- end }}
              {{- end }}
            - name: ONYXIA_URL
              value: "https://marimo-${ONYXIA_RANDOM_SUBDOMAIN}.${ONYXIA_DOMAIN}"
            - name: ONYXIA_RANDOM_SUBDOMAIN
              value: "${ONYXIA_RANDOM_SUBDOMAIN}"
            - name: ONYXIA_DOMAIN
              value: "${ONYXIA_DOMAIN}"
          startupProbe:
            httpGet:
              path: /healthz
              port: http
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
