apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "marimo.fullname" . }}
  labels:
    {{- include "marimo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "marimo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "marimo.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "marimo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      # Add init container to verify service account exists
      initContainers:
        - name: check-sa-exists
          image: "bitnami/kubectl:latest"
          command:
            - "/bin/bash"
            - "-c"
            - |
              echo "Waiting for service account to be available..."
              until kubectl get serviceaccount {{ include "marimo.serviceAccountName" . }} -n {{ .Release.Namespace }} &> /dev/null; do
                echo "ServiceAccount not found yet, waiting..."
                sleep 2
              done
              echo "ServiceAccount is available!"
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "/bin/sh"
            - "-c"
            - "marimo server --port ${MARIMO_PORT} --host 0.0.0.0 --allow-origins ${MARIMO_ALLOW_ORIGINS}"
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "marimo.fullname" . }}-configmap
          {{- if or .Values.onyxia.s3.enabled .Values.onyxia.auth.enabled }}
            - secretRef:
                name: {{ include "marimo.fullname" . }}-secret
          {{- end }}
          livenessProbe:
            httpGet:
              path: /api/status
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/status
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: marimo-data
              mountPath: {{ .Values.persistence.mountPath }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: marimo-data
          {{- if .Values.persistence.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
          {{- else }}
          persistentVolumeClaim:
            claimName: {{ include "marimo.fullname" . }}-pvc
          {{- end }}
      {{- end }}