{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "marimo.fullname" . }}
  labels:
    onyxia/service: "true"
    onyxia/type: "service"
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    onyxia/service: "true"
    onyxia/service-type: "http"
    onyxia/service-port: "8080"
    onyxia/type: "service"
    onyxia/random-subdomain: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.tls: "false"
spec:
  ingressClassName: traefik
  rules:
    - host: marimo-${ONYXIA_RANDOM_SUBDOMAIN}.${ONYXIA_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "marimo.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
{{- end }}
