apiVersion: v1
kind: Service
metadata:
  name: {{ include "marimo.fullname" . }}
  labels:
    app: {{ include "marimo.name" . }}
    release: {{ .Release.Name }}
    onyxia/service: "true"
  annotations:
    onyxia/service: "true"
    onyxia/service-port: "8080"
    onyxia/service-type: "http"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "marimo.name" . }}
    release: {{ .Release.Name }}
    onyxia/service: "true"
