apiVersion: v1
kind: Namespace
metadata:
  name: onyxia
  labels:
    toolkit.fluxcd.io/tenant: datadrivet-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: onyxia
  namespace: onyxia
spec:
  interval: 24h
  url: https://inseefrlab.github.io/onyxia
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: onyxia
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: onyxia
      version: 10.x.x
      sourceRef:
        kind: HelmRepository
        name: onyxia
        namespace: onyxia
      interval: 1m
  values:
    ingress:
      enabled: false
    api:
      env:
        authentication.mode: "openidconnect"
        oidc.issuer-uri: "https://auth.platform.datadrivet.ai/auth/realms/datadrivet"
        oidc.clientID: "onyxia"

      # Services available
      catalogs:
        - id: "IDE"
          name: "IDEs"
          description: "Services for IDE"
          location: "https://inseefrlab.github.io/helm-charts-interactive-services"
          maintainer: "andreas.fred-ojala@knowit.se" #Do we have a common email for us?
          status: "PROD"
          highlightedCharts:
            - "jupyter-python"
            - "vscode-python"
          type: "helm"
        - id: "knowit"
          name: "Knowit Charts"
          description: "For exploring data"
          maintainer: "andreas.fred-ojala@knowit.se"
          location: "https://afredojala.github.io/onyx-helmcharts"
          status: "PROD"
          highlightedCharts:
            - vscode-python
          type: helm
        - id: "vibe-coding"
          name: "Data stuff"
          description: "For exploring data"
          maintainer: "jimmy.flatting@knowit.se"
          location: "https://jimmyflatting.github.io/helm-charts"
          status: "PROD"
          type: helm

        
      # Regions
      regions:
        - id: "default"
          name: "Default"
          description: "Default Region for Datadrivet"
          services:
            type: "KUBERNETES"
            singleNamespace: true
            authenticationMode: "serviceAccount"
            expose: 
              domain: "platform.datadrivet.ai"
          data:
            S3:
              URL: "https://minio.platform.datadrivet.ai"
              pathStyleAccess: true
              sts:
                durationSeconds: 86400
                oidcConfiguration:
                  clientID: "onyxia-minio"            
              workingDirectory:
                bucketMode: "multi"
                bucketNamePrefix: "user-"
                bucketNamePrefixGroup: "project-"
          vault:
            URL: "https://vault.platform.datadrivet.ai"
            kvEngine: "onyxia-kv"
            role: "onyxia-user"
            authPath: "jwt"
            prefix: "user-"
            groupPrefix: ""
            oidcConfiguration:
              issuerURI: "https://auth.platform.datadrivet.ai/auth/realms/datadrivet"
              clientID: "vault"