apiVersion: v2
name: marimo
description: A Helm chart for deploying Marimo notebooks
appVersion: 1.0.0
version: 0.1.0
icon: https://raw.githubusercontent.com/marimo-team/marimo/main/docs/_static/marimo.svg
dependencies:
  - name: library-chart
    repository: https://afredojala.github.io/onyx-helmcharts
    version: 1.5.21