apiVersion: v2
name: marimo
description: A Helm chart for Marimo interactive Python notebooks in Onyxia Datalabs
type: application
version: 0.1.0
appVersion: "latest"
keywords:
  - marimo
  - python
  - notebook
  - interactive
  - datascience
home: https://github.com/marimo-team/marimo
sources:
  - https://github.com/marimo-team/marimo
maintainers:
  - name: Jimmy Flatting
    email: jimmy.flatting@knowit.se
# Add these Onyxia-specific annotations
annotations:
  onyxia.sh/category: "notebook"
  onyxia.sh/logo: "https://raw.githubusercontent.com/marimo-team/marimo/main/docs/public/android-chrome-512x512.png"
  onyxia.sh/version: "0.1.0"
  onyxia.sh/description: "Marimo is a reactive notebook for Python"
  onyxia.sh/displayName: "Marimo Notebook"