apiVersion: v2
name: marimo
description: A Helm chart for deploying Marimo notebooks
version: 0.1.1
appVersion: 1.0.0
dependencies:
- name: library-chart
  repository: https://afredojala.github.io/onyx-helmcharts
  version: 1.5.21