replicaCount: 1
image:
  repository: marimo
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: marimo.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
