replicaCount: 1
image:
  repository: ghcr.io/marimo-team/marimo
  tag: "latest"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: marimo-${ONYXIA_RANDOM_SUBDOMAIN}.${ONYXIA_DOMAIN}
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 128Mi
nodeSelector: {}
tolerations: []
affinity: {}
onyxia:
  friendlyName: "Marimo"
  service:
    port: 8080
