global:
  suspend: false

s3:
  enabled: false
spark:
  default: false
discovery:
  hive: false
  mlflow: false
  metaflow: false
  chromadb: false

# Add authentication configuration
authentication:
  enabled: false
  token: ""  # Will generate a random token if not specified

replicaCount: 1

image:
  repository: ghcr.io/marimo-team/marimo
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  image:
    custom:
      enabled: false
      version: "ghcr.io/marimo-team/marimo:latest"
ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: default-stripprefix@kubernetescrd
    traefik.ingress.kubernetes.io/service.serversscheme: http
    traefik.ingress.kubernetes.io/service.passhostheader: "true"
  tls: []
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 128Mi
nodeSelector: {}
tolerations: []
affinity: {}
serviceAccount:
  create: true
  annotations: {}
  name: ""
podSecurityContext:
  fsGroup: 100
securityContext: {}
environment:
  user: onyxia
  group: users
networking:
  type: ClusterIP
  clusterIP: None
  service:
    port: 8080
onyxia:
  friendlyName: "Marimo"
  description: "Marimo is a reactive Python notebook that's designed to be used both as an interactive development environment and as a data app framework."
  icon: "https://raw.githubusercontent.com/marimo-team/marimo/main/docs/_static/marimo.svg"
  service:
    port: 8080
  randomSubdomain: ${ONYXIA_RANDOM_SUBDOMAIN}
  domain: ${ONYXIA_DOMAIN}
  environment:
    ONYXIA_URL: "https://marimo-${ONYXIA_RANDOM_SUBDOMAIN}.${ONYXIA_DOMAIN}"
    ONYXIA_RANDOM_SUBDOMAIN: "${ONYXIA_RANDOM_SUBDOMAIN}"
    ONYXIA_DOMAIN: "${ONYXIA_DOMAIN}"

kubernetes:
  enabled: true
  role: "view"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

route:
  enabled: false
  annotations: []
    # route.openshift.io/termination: "reencrypt"
  hostname: chart-example.local
  userHostname: chart-example-user.local
  tls:
    termination: edge
    # key:
    # certificate:
    # caCertificate:
    # destinationCACertificate:
  wildcardPolicy: None

repository:
  configMapName: ""
  pipRepository: ""
  condaRepository: ""
  mavenRepository: ""

userPreferences:
  darkMode: false
  language: "en"

init:
  standardInitPath: ""
  regionInit: ""
  personalInit: ""
  personalInitArgs: ""

# Add persistence configuration if it doesn't exist
persistence:
  enabled: false
  existingClaim: ""

# Array with (templated) extra environment variables to be made accessible within the service
# e.g:
# extraEnvVars:
#   - name: FOO
#     value: "bar"
extraEnvVars: []
