image:
  repository: ghcr.io/marimo-team/marimo
  tag: "latest"

# Onyxia specific configurations
onyxia:
  enabled: true
  instance:
    name: marimo
    friendlyName: Marimo Notebook
    description: Interactive Python notebooks with Marimo
    category: Development
    logo: https://raw.githubusercontent.com/marimo-team/marimo/main/docs/_static/logo.png
    initScript: |
      pip install marimo
      marimo init my_notebook.py

# Service configuration
service:
  type: ClusterIP
  port: 8000

# Ingress configuration
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"

# Resource configuration
resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 2
    memory: 4Gi

# Security context
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

# Environment variables
env:
  - name: MARIMO_SERVER_HOST
    value: "0.0.0.0"
  - name: MARIMO_SERVER_PORT
    value: "8000"

# ServiceAccount configuration
serviceAccount:
  create: true
  name: ""
  annotations: {}

# Autoscaling configuration
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
  scaleDownDelaySeconds: 300
  scaleUpDelaySeconds: 0