# Minimal configuration for Marimo
replicaCount: 1

image:
  repository: ghcr.io/marimo-team/marimo
  tag: "latest"

service:
  port: 8080

serviceAccount:
  create: true
  name: ""

ingressRoute:
  enabled: true
  host: ""  # Will be set by Onyxia
  path: "/"
  tls:
    enabled: true
    secretName: ""  # Will be set by Onyxia
    certResolver: "le"
    clusterIssuer: "letsencrypt-prod"

ingress:
  certManager:
    clusterIssuer: "letsencrypt-prod"

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

persistence:
  enabled: true
  size: 10Gi
  mountPath: /home/marimo/notebooks

# Basic environment variables
environment:
  MARIMO_PORT: 8080
  MARIMO_ALLOW_ORIGINS: "*"

# Onyxia integration
onyxia:
  s3:
    enabled: false
  auth:
    enabled: false