apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "marimo.fullname" . }}-marimo-config
  labels:
    {{- include "marimo.labels" . | nindent 4
data:
  marimo.toml: |
    [display]
    theme = "dark"
    code_editor_font_size = 14
    cell_output = "above"
    default_width = "medium"
    dataframes = "rich"

    [save]
    autosave = "after_delay"
    autosave_delay = 1000
    format_on_save = false

    [snippets]
    custom_paths = []
    include_default_snippets = true

    [completion]
    activate_on_typing = true
    copilot = false

    [runtime]
    auto_instantiate = true
    auto_reload = "off"
    on_cell_change = "autorun"
    watcher_on_save = "lazy"
    output_max_bytes = 8000000
    std_stream_max_bytes = 1000000
    pythonpath = []

    [language_servers.pylsp]
    enabled = true
    enable_mypy = true
    enable_ruff = true
    enable_flake8 = false
    enable_pydocstyle = false
    enable_pylint = false
    enable_pyflakes = false

    [keymap]
    preset = "default"

    [keymap.overrides]

    [package_management]
    manager = "uv"

    [server]
    browser = "default"
    follow_symlink = false

    [formatting]
    line_length = 79 